site_name: Learn Scade
site_description: 'ScadeSuit学习教程'
site_url: https://learnscadesuit.github.io/
repo_url: https://github.com/LearnScadeSuit/LearnScadeSuit.github.io

nav:
    - 首页: '01 首页.md'
    - 目录:
      - 介绍: '03 介绍.md'
      - 安装: '04 安装.md'
      - 参考文档: '05 参考文档.md'
      - SCADE Suit:
          - 简介: 'ScadeSuit/01 简介.md'
          - Scade工程: 'ScadeSuit/02 Scade工程.md'
      - SCADE Display:
          - 简介: 'ScadeDisplay/01 简介.md'
      - SCADE Architect:
          - 简介: 'ScadeArchitect/01 简介.md'
      - SCADE A661:
          - 简介: 'ScadeA661/01 简介.md'
      - SCADE Test:
          - 简介: 'ScadeTest/01 简介.md'
      - 实战:
          - 简介: '实战/01 简介.md'
    - 代码仓库: '02 代码仓库.md'